name: Pullrequest CI
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - name: Set up Haskell
      uses: haskell/actions/setup@v2

    - name: Check out repo
      uses: actions/checkout@v3

    - name: Read the Cabal cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          message-index/dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
       # key: cabal-cache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install dependencies
      run: |
        cabal build all --only-dependencies

    - name: Update the Cabal index
      run: |
        cabal update

    - name: Check if site.hs is formatted using ormolu
      uses: mrkkrp/ormolu-action@v6
      with:
        pattern: |
          **/site.hs

    - name: Build with Hakyll
      working-directory: message-index
      run: cabal run site build
